"""initial schema

Revision ID: b1983a983dd6
Revises: 
Create Date: 2026-08-06 17:20:01.759562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1983a983dd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gpay_upi_id', sa.String(length=120), nullable=True),
    sa.Column('phonepe_upi_id', sa.String(length=120), nullable=True),
    sa.Column('paytm_upi_id', sa.String(length=120), nullable=True),
    sa.Column('merchant_name', sa.String(length=120), nullable=False),
    sa.Column('merchant_phone', sa.String(length=20), nullable=False),
    sa.Column('payment_note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'COLLECTOR', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='customer_status'), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_access_token'), 'customers', ['access_token'], unique=True)
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=True)
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_table('monthly_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUBMITTED', 'VERIFIED', name='payment_status'), nullable=False),
    sa.Column('subscription_status', sa.Enum('PENDING', 'ACTIVE', name='subscription_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'month', 'year', name='uq_customer_month_year')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SMS', 'WHATSAPP', name='notification_type'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'SIMULATED', name='notification_status'), nullable=False),
    sa.Column('sent_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.Enum('UPI_GPAY', 'UPI_PHONEPE', 'UPI_PAYTM', 'CASH', name='payment_mode'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_reference', sa.String(length=120), nullable=True),
    sa.Column('submitted_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['monthly_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('notifications')
    op.drop_table('monthly_subscriptions')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_access_token'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('plans')
    # ### end Alembic commands ###
